[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = ["cd backend && npm install --only=production"]

[phases.build]
cmds = ["echo 'No build step needed'"]

[start]
cmd = "cd backend && npm start"

